# SPDX-FileCopyrightText: Copyright (c) 2023 - 2024 NVIDIA CORPORATION & AFFILIATES.
# SPDX-FileCopyrightText: All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Model configuration
model:
  # Spatial resolution [depth, width] of the velocity model. Should be a
  # multiple of 2**N where N is the number of levels in the UNet, defined by
  # 'channel_mult'. Note: if velocity models from the dataset are at a
  # different resolution, interpolation is performed to match 'x_resolution'.
  x_resolution: [80, 80]
  # Number of channels in the velocity model, should be equal to the number
  # of variables (e.g. 3 for Vp, Vs, rho).
  x_channels: 3
  # Spatial resolution [time steps, # receivers along width] of the seismic
  # data. The second dimension should be equal to the width of the velocity
  # model.
  y_resolution: [1000, 80]
  # Number of channels in the seismic data. Should be equal to number of
  # sources * number of variables observed (e.g. 2 for ux, uz)
  y_channels: 10
  # Number of channels in the encoder hidden layer.
  encoder_hidden_channels: 128
  # Number of encoder blocks.
  num_encoder_blocks: 4
  # Number of channels in the positional embedding grid.
  N_grid_channels: 20
  # Base multiplier for the number of channels in the UNet.
  model_channels: 128
  # Multipliers for the number of channels at each level in the UNet.
  channel_mult: [1, 2, 2, 2, 2]
  # Number of blocks in the UNet.
  num_blocks: 4
  # Additional keyword arguments for the UNet. Should be a dictionary. Set to
  # null to use default parameters.
  unet_kwargs: null

dataset:
  # Training data directory that should contain a subdirectory "samples/"" and
  # a file stats.json
  directory: <path_to_dataset>
  # Variables in the velocity model.
  x_vars: ["vp", "vs", "rho"]
  # Variables in the seismic data.
  y_vars: ["vx", "vz"]

# Training configuration
training:
  # Batch size per device for training
  batch_size_per_device: 64
  # Maximum number of epochs
  max_epochs: 400 
  # Base learning rate
  lr: 5.0e-4
  # Weight decay for optimizer
  weight_decay: 1.0e-4
  # Number of workers for data loading
  num_workers: 4
  # Learning rate scheduler
  scheduler:
    # Minimum learning rate
    eta_min: 5.0e-6

# Validation configuration
val:
  # Batch size per device for validation
  batch_size_per_device: 64
  # Number of workers for validation data loading
  num_workers: 4

# I/O configuration
io:
  # Whether to load a checkpoint
  load_checkpoint: false
  # Directory to save/load checkpoints
  checkpoint_dir: "./checkpoints/"
  # Save checkpoint every N epochs
  checkpoint_freq: 10
  # Log frequency (in batches)
  log_freq: 10

# Wandb configuration
wandb:
  # "online", "offline", or "disabled"
  mode: "offline"
  # Directory to save wandb logs
  results_dir: "./wandb/"
  # Entity (username or team name) for Weights & Biases
  entity: <wandb_entity_name>
