hydra:
    job:
          chdir: false
          name: dit_regression_local
    run:
          dir: ./output/${hydra:job.name}
    searchpath:
          - pkg://conf/base

defaults:
    - dataset: custom
    - model: dit_regression
    - training: dit_regression

dataset:
    type: norway
    data_path: /Users/simon/Datasets/Norway/HCLIM3/preprocessed_large/NorCP_AROME_EC-EARTH
    stats_path: /Users/simon/Datasets/Norway/HCLIM3/preprocessed_large/NorCP_AROME_EC-EARTH
    invariant_variables_path: /Users/simon/Datasets/Norway/
    years: [1986, 1987]
    output_variables: ['precipitation']
    input_variables: ["hus500","hus850","ua500","ua850","va500","va850","ta500","ta850"]
    invariant_variables: ["elevation"]
    bounds: large

validation:
    years: [2004]

model:
    model_args:
        patch_size: 8
        hidden_size: 128
        depth: 2
        num_heads: 4
        attention_backend: timm

training:
    hp:
        training_duration: 20
        batch_size_per_gpu: 1
        total_batch_size: 1
        lr: 0.0001
    perf:
        dataloader_workers: 0
    io:
        print_progress_freq: 5
        save_checkpoint_freq: 100000
        checkpoint_dir: output/test_dit_regression
        save_n_recent_checkpoints: 1
        validation_freq: 20
        validation_steps: 2

wandb:
    mode: disabled
    results_dir: "./wandb"
    watch_model: false
