# SPDX-FileCopyrightText: Copyright (c) 2023 - 2024 NVIDIA CORPORATION & AFFILIATES.
# SPDX-FileCopyrightText: All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Diffusion training config based on HP search best result (trial 7)
# Normal distribution, lr=5.19e-4, batch=128, sigma_data=0.869, P_mean=0.750, P_std=0.844
# Regression backbone: reg_07_flexi_p125 @ step 1700096

hydra:
    job:
          chdir: false
          name: tr_diff_hp_high75
    run:
          dir: ./output/${hydra:job.name}
    searchpath:
          - pkg://conf/base # Do not modify

defaults:
    - dataset: custom
    - model: diffusion
    - model_size: normal
    - training: ${model}

model:
    model_args:
        attn_resolutions: [16]

dataset:
    type: norway
    data_path: /data/Norway/HCLIM3/preprocessed_large/NorCP_AROME_EC-EARTH
    stats_path: /data/Norway/HCLIM3/preprocessed_large/NorCP_AROME_EC-EARTH
    invariant_variables_path: /data/Norway/HCLIM3/
    output_variables: ['precipitation']
    input_variables: ["hus500","hus850","ua500","ua850","va500","va850","ta500","ta850"]
    invariant_variables: ["elevation"]
    bounds: large
    years: [1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001]
    extreme_percentile: 75.0

validation:
    years: [2003, 2004]

training:
    hp:
        training_duration: 1000000 #1500000
        total_batch_size: 128
        batch_size_per_gpu: 4
        lr: 5.185225311935692e-4
        distribution: normal
        P_mean: 0.7499199835165111
        P_std: 0.8440688577987278
        sigma_data: 0.8690460756242084
    io:
        print_progress_freq: 100000
        regression_checkpoint_path: /checkpoints/hp_reg_grid/reg_07_flexi_p125/checkpoints_regression/UNet.0.1700096.mdlus
        checkpoint_dir: /checkpoints/tr_diff_hp_high75
        save_checkpoint_freq: 100000
        save_n_recent_checkpoints: 20

wandb:
    mode: online
    results_dir: "./wandb"
    watch_model: false
