# Norway symmetric 3-hour temporal regression.

defaults:
  - /base_regression_norway
  - _self_

hydra:
  job:
    name: tr_reg_norway_sym3h
  run:
    dir: ./output/${hydra:job.name}

dataset:
  temporal_inputs:
    offset_hours: [-3, 0, 3]
    boundary: drop
    strict_time_step_hours: 3

training:
  hp:
    training_duration: 2000000
    total_batch_size: 256
    batch_size_per_gpu: 4
    lr: 1.0e-4
    lr_decay: 1.0
    loss_function: flexiloss
    flexi_loss_p: [1.25]
    flexi_loss_d: [1]
  io:
    print_progress_freq: 100000
    checkpoint_dir: /checkpoints/temporal_regression/norway_sym3h
    save_checkpoint_freq: 100000
    save_n_recent_checkpoints: 20
    validation_freq: 100000
    validation_steps: 10

wandb:
  mode: online
  results_dir: "./wandb"
  watch_model: false
